meta:
  title_template: "%s | Zenix"
  description: OS for Intelligence
  author: Zenix Team
  favicon: /favicon.png

site:
  origin: https://www.zenixos.org
  view_transitions: true
  skip: [ archive, draft ]

sitemap:
  enabled: true

rss:
  title: Zenix Essays
  collection: essay
  enabled: true

content:
  sections: true

collections:
  essay:
    include: [ essay/ ]
    skip: [ skip ]
    sort: date desc
    navigation: true

server:
  reload: true
