meta:
  title_template: "%s | Zenix"
  description: OS for Intelligence
  author: Zenix Team
  favicon: /favicon.png

site:
  origin: https://www.zenixos.org
  view_transitions: true

sitemap:
  enabled: true

rss:
  title: Zenix Blog
  collection: blog
  enabled: true

content:
  sections: true

collections:
  blog:
    include: [ blog/ ]
    skip: [ skip ]
    sort: date desc

server:
  reload: true
